POST http://localhost:8080/prestamo/save
Content-Type: application/json

{
  "fecha": "2023-05-24T10:30:00",
  "monto": 3000,
  "tipoPrestamo": "SEMANAL_13",
  "vencimiento": "2023-06-24T10:30:00",
  "interes": 900,
  "cuotas": 13,
  "estado": 0,
  "pagares": [],
  "cliente":{
    "idCliente":1
  }
}
